name: docker build and push
on:
    push:
      branches:
        - 'main'

jobs:
    docker:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main
            - name: Login to Github Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ghcr.io/jmoney/secrets-manager-poc:latest
